# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'AirCrashlytics' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
    
    pod 'Firebase/Analytics', '10.24.0'
    pod 'Firebase/Crashlytics', '10.24.0'
    pod 'Firebase/Messaging', '10.24.0'

  # Pods for AirCrashlytics

end
