# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AirCrashlytics' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#	pod 'Fabric', '1.10.2'
#    pod 'Crashlytics', '3.14.0'
    pod 'Firebase/Analytics', '6.34.0'
    pod 'Firebase/Crashlytics', '6.34.0'
  # Pods for AirCrashlytics

end
