# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AirCrashlytics' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    
    pod 'Firebase/Analytics', '8.10.0'
    pod 'Firebase/Crashlytics', '8.10.0'
    pod 'Firebase/Messaging', '8.10.0'

  # Pods for AirCrashlytics

end
